[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "ff_ac"
version = "0.1.0"
description = "DarSIA analysis for AC FF data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "darsia",
    "natsort",
    "pytest",
    "deepdiff",
    "optuna>=4.9.0",
]

[project.optional-dependencies]
cuda = [
    "cupy-cuda13x[ctk]>=14.1.1,<15",
]
opencl = [
    "mako>=1.3,<2",
    "pyopencl>=2026.1.2,<2027",
]

[tool.uv]
package = false

[tool.uv.sources]
darsia = { path = "external/darsia", editable = true }
