"""Generate per-experiment ff_ac TOML configs for the Albus (AC) series."""

from __future__ import annotations

import argparse
import logging
import re
from pathlib import Path

import generate_protocols as gp  # shared phase-folder detection (robust naming)

LOG = logging.getLogger("generate_configs")
FOLDER_RE = re.compile(r"(?P<date>\d{6})_(?P<time>\d{6})_(?:AC(?P<num>\d+)_)?(?P<phase>\w+)")

LABELING = './data/DSC28507_segmented.png'
CURVATURE_PTS = "[[0, 57], [3023, 64], [3000, 5378], [0, 5374]]"
RIG_WIDTH, RIG_HEIGHT = 0.90, 0.49
COLORCHECKER = "upper_right"

TIME_GRID = [
    ("inj1_fine",  "00:00:00", "00:10:00", 21, "00:00:15"),
    ("inj1_body",  "00:10:00", "00:55:00", 16, "00:01:30"),
    ("inj2_onset", "00:55:00", "01:15:00", 11, "00:01:00"),
    ("inj2_body",  "01:15:00", "02:30:00", 16, "00:02:30"),
    ("rest_early", "02:30:00", "06:00:00", 15, "00:07:00"),
    ("rest_mid",   "06:00:00", "24:00:00", 13, "01:30:00"),
    ("rest_late",  "24:00:00", "120:00:00", 13, "08:00:00"),
]


def first_images(folder: Path, n: int = 3) -> list:
    jpgs = sorted([p.name for p in folder.glob("*.JPG")] +
                  [p.name for p in folder.glob("*.jpg")])
    return jpgs[:n]


def toml_path(p: str) -> str:
    return p.replace("\\", "\\\\")


def build_config(num, exp_dir, data_root, results_root, protocols_rel):
    inj_folders, rest_folders = gp.list_phase_folders(exp_dir)
    if not inj_folders:
        LOG.warning("AC%s: no injection folder, skipping", num)
        return None
    base = first_images(inj_folders[0], 3)
    if not base:
        LOG.warning("AC%s: no baseline images", num)
        return None

    def win_join(*parts):
        return "\\".join(str(p).rstrip("\\/") for p in parts)

    root_str = str(data_root)
    folder_csv = []
    for ptag, group in (("inj", inj_folders), ("rest", rest_folders)):
        for k, f in enumerate(group):
            folder_csv.append((win_join(root_str, exp_dir.name, f.name),
                               gp.imaging_csv_name(ptag, k, len(group))))
    folders = [fc[0] for fc in folder_csv]
    folders_toml = ", ".join(f'"{toml_path(f)}"' for f in folders)
    base_paths = ", ".join(f'"{b}"' for b in base)
    pr = protocols_rel.rstrip("/")
    tag = f"ac{num}"

    L = []
    L.append("##################################################")
    L.append(f"# Albus AC{num}  (generated by generate_configs.py)")
    L.append("##################################################")
    L.append("[id]")
    L.append(f'run_id = "Albus AC{num}"')
    L.append("")
    L.append("[data]")
    L.append(f"folders = [{folders_toml}]")
    L.append(f'results = "{toml_path(results_root)}\\\\{tag}"')
    L.append(f'baseline = "{base[0]}"')
    L.append("")
    L.append("[data.path.baseline]")
    L.append(f"paths = [{base_paths}]")
    L.append("")
    L.append("# Shared time grid: dense through BOTH injections, exponential in rest.")
    L.append("# t=0 = injection ramp-up start; identical across all experiments.")
    for name, start, end, n_pts, tol in TIME_GRID:
        L.append(f"[data.interval.{name}]")
        L.append(f'start = "{start}"')
        L.append(f'end = "{end}"')
        L.append(f"num = {n_pts}")
        L.append(f'tol = "{tol}"')
        L.append("")
    L.append("[protocols]")
    L.append(f'injection = "{pr}/{tag}/injection_protocol.csv"')
    L.append(f'pressure_temperature = "{pr}/{tag}/pressure_temperature_protocol.csv"')
    # NB: imaging_mode only matters if the imaging-protocol SETUP step is run
    # (it re-derives times from images). Our pre-generated pure-protocol CSVs are
    # authoritative for analysis, so skip `setup.py --protocol`. "ctime" matches
    # the tested run_jakub/ac60.toml and avoids EXIF if the step is ever run.
    L.append('imaging_mode = "ctime"')
    L.append("")
    L.append("[protocols.imaging]")
    for fpath, csvname in folder_csv:
        L.append(f'"{toml_path(fpath)}" = "{pr}/{tag}/{csvname}"')
    L.append("")
    L.append("[labeling]")
    L.append(f'colored_image = "{LABELING}"')
    L.append("")
    L.append("[corrections]")
    L.append("[corrections.type]")
    L.append('type = "float32"')
    L.append("[corrections.drift]")
    L.append(f'colorchecker = "{COLORCHECKER}"')
    L.append("[corrections.curvature.crop]")
    L.append(f"pts_src = {CURVATURE_PTS}")
    L.append(f"width = {RIG_WIDTH}")
    L.append(f"height = {RIG_HEIGHT}")
    L.append("")
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--albus-root", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--data-root", required=True, type=Path)
    ap.add_argument("--results-root", default="E:\\ff_ml4gcs")
    ap.add_argument("--protocols-rel", default="protocols")
    ap.add_argument("--experiments", nargs="*", default=[])
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    root = args.albus_root
    if args.all:
        exps = sorted([d for d in root.iterdir()
                       if d.is_dir() and re.fullmatch(r"AC\d+", d.name)],
                      key=lambda d: int(d.name[2:]))
    else:
        exps = [root / e for e in args.experiments]

    args.out.mkdir(parents=True, exist_ok=True)
    written = 0
    for exp in exps:
        if not exp.exists():
            LOG.error("Missing %s", exp)
            continue
        num = int(exp.name[2:])
        cfg = build_config(num, exp, args.data_root, args.results_root, args.protocols_rel)
        if cfg is None:
            continue
        (args.out / f"ac{num}.toml").write_text(cfg, encoding="utf-8")
        LOG.info("Wrote %s/ac%s.toml", args.out, num)
        written += 1
    LOG.info("Generated %d config(s)", written)


if __name__ == "__main__":
    main()
